sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly
  - 1.18.0

script:
  - cargo check --bin json-benchmark
  - cargo check --bin binary-benchmark --no-default-features --features 'binary performance all-files'
