[package]
name = "json-benchmark"
version = "0.0.1"
authors = ["dtolnay@gmail.com"]

[dependencies]
dtoa = "*"
fastwrite = "*"
getopts = "*"
json = { version = "0.10", optional = true }
rustc-serialize = { version = "*", optional = true }
serde = { version = "0.8", optional = true }
serde_json = { version = "0.8", optional = true }
serde_macros = { version = "0.8", optional = true }
time = "*"

[features]
default = ["performance", "all-libs", "all-files"]
all-libs = ["lib-serde", "lib-json-rust", "lib-rustc-serialize"]
all-files = ["file-canada", "file-citm-catalog", "file-twitter"]
performance = ["parse-dom", "stringify-dom", "parse-struct", "stringify-struct"]
lib-serde = ["serde", "serde_macros", "serde_json"]
lib-json-rust = ["json"]
lib-rustc-serialize = ["rustc-serialize"]
file-canada = []
file-citm-catalog = []
file-twitter = []
parse-dom = []
stringify-dom = []
parse-struct = []
stringify-struct = []

[profile.release]
debug = true
