[package]
name = "json-benchmark"
version = "0.0.1"
authors = ["dtolnay@gmail.com"]

[dependencies]
dtoa = "*"
fastwrite = "*"
json = { git = "https://github.com/maciejhirsz/json-rust", branch = "benches" }
rustc-serialize = "*"
serde = "*"
serde_json = { git = "https://github.com/serde-rs/json", branch = "json-benchmark" }
serde_macros = "*"
time = "*"

[features]
default = ["performance"]
performance = []
conformance = []
